title:  Prography
email: contact@prography.org
description: 세상에 필요한 IT 서비스를 만드는 허브 <b>프로그라피</b> 기술블로그 입니다 :) 
baseurl: ''
url: 'https://prography-tech.github.io/'
timezone: Asia/Seoul 

repository: prography-tech/prography-tech.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown


kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-youtube

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
author: contact@prography.org
image: 'assets/images/home.jpg'
asset_url: /assets

github_url:
  username: prography-develop

google_analytics:
  ua: 'UA-155207559-1'

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
